### ISSUE TITLE
make cache shared

### ISSUE THREAD

**Issue by calvinfo** [segment-integrations/integration-hubspot#1]
Was looking through the code and realized that in one of the refactors the cache never gets shared. It gets created on initialize, but won't be used between requests, so we end up doing a lot more requests for settings than we need to. Not causing bugs, but probably running through more requests than we need.

https://github.com/segmentio/integration-hubspot/blob/32d87742770eafbe21f2014cb0f7161d411970fb/lib/index.js#L38-L41

**Comment by hankim813** [comment]
Added to JIRA for internal tracking https://segment.atlassian.net/browse/INT-217
