### ISSUE TITLE
Global variables cause clashes with other scripts

### ISSUE THREAD

**Issue by Jannis** [segment-integrations/integration-hubspot#21]
When loading the minified version of the HubSpot integration script for Segment, the global variable `t` is defined, which clashes with our own minified scripts. Ideally, this script would not define any globals other than a single, well-defined variable for the module.

I'm happy to discuss this further or provide help in fixing the problem.

**Comment by hankim813** [comment]
Hey there @Jannis! I'm guessing you probably meant to open this issue with our JS Hubspot integration repo here: https://github.com/segment-integrations/analytics.js-integration-hubspot

but to answer your question here: it doesn't look like hubspot is using a `window.t`: https://github.com/segment-integrations/analytics.js-integration-hubspot/blob/master/lib/index.js#L18

Regardless even if they did, that is something beyond our control unfortunately :( If a partner JS library sets a global variable with their script, we can't change that behavior
