### ISSUE TITLE
change to use hubspots create_or_update

### ISSUE THREAD

**Issue by calvinfo** [segment-integrations/integration-hubspot#3]
http://developers.hubspot.com/docs/methods/contacts/create_or_update

must have been added more recently

**Comment by iancanderson** [comment]
Are there plans to add this soon? This would save a lot on the # of API calls made to Hubspot

**Comment by hankim813** [comment]
@iancanderson super sorry -- we have not been good tracking issues on github until more recently 😅 With that said, this is in our backlog and triaging it internally. Can't say anything definitive on ETA but it is on our roadmap.
